### ISSUE TITLE
1.19.2

### ISSUE THREAD

**Issue by TheStaticVoid** [Laith471/Avaritia-Fabric#1]
I hate to be that guy but I was wondering if a backport to 1.19.2 was considered?

If you personally don't want to, I could work on it and PR it here if you'd like.

**Comment by Laith471** [comment]
I don't think this is the best thing to do cuz the mod is still under development. When it reaches to stable state I'll message you if you want to make a PR in that time, or maybe I’ll backport it by myself.
Thanks.
