### ISSUE TITLE
This is the best Avaritia port i have ever seen in my life.

### ISSUE THREAD

**Issue by Leclowndu93150** [Laith471/Avaritia-Fabric#2]
Hey i really like your mod, i  will try having it in my forge modpack using https://modrinth.com/mod/connector (i hope it will work)

i know that the mod is still in the works but do you plan on adding all the cool effects ? Just the ingot and catalyst managed to convince me !
Is there a class i can access using KubeJS to give any item that same moving effect ?

**Comment by Leclowndu93150** [comment]
update: i got it to run on forge

**Comment by Laith471** [comment]
Yes I’ll try to add them all.
I didn’t make compatibility for KubeJS i will try to add it, but in the future cuz the mod is still under development.
Thanks for your words

**Comment by Leclowndu93150** [comment]
> Yes I’ll try to add them all. I didn’t make compatibility for KubeJS i will try to add it

![image](https://github.com/Laith471/Avaritia-Fabric/assets/73310949/0d25b888-ad77-4ca8-a7b7-c4402624dae1)

basicaly KubeJS can do stuff like that, so im wondering if there is a class i can access to do that effect
