### ISSUE TITLE
world breaker cannot one shot blocks with "no tool"

### ISSUE THREAD

**Issue by Leclowndu93150** [Laith471/Avaritia-Fabric#4]

**Comment by Laith471** [comment]
Can you explain more I didn’t understand 😅

**Comment by Leclowndu93150** [comment]
> Can you explain more I didn’t understand 😅

so basicaly if the block doesn't have a set tool to be broken with (example: shovel for dirt and pickaxe for cobble") then the world breaker will not one shot the block (or any other tool btw)
