### ISSUE TITLE
Contributing?

### ISSUE THREAD

**Issue by cph101** [Laith471/Avaritia-Fabric#6]
Hi,

I am putting this on as an issue, since I can find no other way of contacting you. Do you think you could add me as a contributor on the repo settings? I would love to help develop this mod.

Some of the things I have in mind is adding screenshots and some status badges to the readme, and a GitHub actions build workflow.

Thanks in advance,
cph101

**Comment by Leclowndu93150** [comment]
you could do that using PRs

**Comment by cph101** [comment]
True
